### ISSUE TITLE
centos and ubuntu demo files do not install xentools

### ISSUE THREAD

**Issue by tschilb252** [ddelnano/packer-plugin-xenserver#22]
Modify the ks-centos8.cfg (centos) and user-data (ubuntu) files to include the installation of xentools.

The plugin mounts the guest-tools.iso in DVD Drive 2 but the scripts for mounting and installing the tools arent part of the deployment.

**Comment by ddelnano** [comment]
While I would expect many users will install xentools in their VMs, I don't think the examples in this repo need to be production ready. The examples should showcase the important features of the packer plugins rather than cater towards specific users needs. The examples already install packages so if someone wants to add xentools, it should be trivial to do so.

I really appreciate you taking the time to submit this issue but I think the examples are easily extendable if xentools needs to be installed.
